name: deploy-pages

triggers:
  push:

jobs:
  deploy:
    image: alios-8u
    steps:
      - uses: checkout
      - uses: deploy-pages
        inputs:
          deploy-dir: ./
          site-name: superme-tshirt
          production-branch: master
